In [1]:
import numpy as np
import pandas as pd

We'll keep our analysis of G7 countries and looking now at DataFrames. As said, a DataFrame looks a lot like a table
<img src="https://camo.githubusercontent.com/097bd658f7b6e6ef396e013ecb737580474b8c00/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f3837323239362f33383135333439322d37326330333263612d333434332d313165382d383066342d3964653930363061353132372e706e67">

In [2]:
df = pd.DataFrame({
    "Population" : [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    "GDP" : [1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075],
      "Surface": [9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067],
      "HDI":[
             0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
      ],
      "Continent": [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
      ]
})

In [3]:
df

   Population       GDP  Surface    HDI Continent
0      35.467   1785387  9984670  0.913   America
1      63.951   2833687   640679  0.888    Europe
2      80.940   3874437   357114  0.916    Europe
3      60.665   2167744   301336  0.873    Europe
4     127.061   4602367   377930  0.891      Asia
5      64.511   2950039   242495  0.907    Europe
6     318.523  17348075  9525067  0.915   America

In [4]:
df.index = [
            'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [5]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [6]:
df.columns

Index(['Population', 'GDP', 'Surface', 'HDI', 'Continent'], dtype='object')

In [7]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Population  7 non-null      float64
 1   GDP         7 non-null      int64
 2   Surface     7 non-null      int64
 3   HDI         7 non-null      float64
 4   Continent   7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes

In [9]:
df.size

35

In [10]:
df.shape

(7, 5)

In [11]:
df.describe()

       Population           GDP       Surface       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [12]:
df.dtypes

Population    float64
GDP             int64
Surface         int64
HDI           float64
Continent      object
dtype: object

In [13]:
df.dtypes.value_counts()

int64      2
float64    2
object     1
dtype: int64

<h3>Indexing, Selection and Slicing</h3>

In [14]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [15]:
df.loc["United Kingdom"]

Population     64.511
GDP           2950039
Surface        242495
HDI             0.907
Continent      Europe
Name: United Kingdom, dtype: object

In [16]:
df.iloc[5]

Population     64.511
GDP           2950039
Surface        242495
HDI             0.907
Continent      Europe
Name: United Kingdom, dtype: object

In [17]:
df["Population"]

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [18]:
df["Population"].to_frame()

                Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

In [19]:
df[["Population", "GDP"]]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [20]:
df[1:3]

         Population      GDP  Surface    HDI Continent
France       63.951  2833687   640679  0.888    Europe
Germany      80.940  3874437   357114  0.916    Europe

In [21]:
df.loc["Italy"]

Population     60.665
GDP           2167744
Surface        301336
HDI             0.873
Continent      Europe
Name: Italy, dtype: object

In [22]:
df.loc["France":"Italy"]

         Population      GDP  Surface    HDI Continent
France       63.951  2833687   640679  0.888    Europe
Germany      80.940  3874437   357114  0.916    Europe
Italy        60.665  2167744   301336  0.873    Europe

In [23]:
df.loc["France":"Italy", "GDP"]

France     2833687
Germany    3874437
Italy      2167744
Name: GDP, dtype: int64

In [24]:
df.loc["France": "Italy", ["Population", "GDP"]]

         Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [25]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [26]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [27]:
df.iloc[0]

Population     35.467
GDP           1785387
Surface       9984670
HDI             0.913
Continent     America
Name: Canada, dtype: object

In [28]:
df.iloc[-1]

Population     318.523
GDP           17348075
Surface        9525067
HDI              0.915
Continent      America
Name: United States, dtype: object

In [29]:
df.iloc[1:3]

         Population      GDP  Surface    HDI Continent
France       63.951  2833687   640679  0.888    Europe
Germany      80.940  3874437   357114  0.916    Europe

In [30]:
df.iloc[[1,4,2]]

         Population      GDP  Surface    HDI Continent
France       63.951  2833687   640679  0.888    Europe
Japan       127.061  4602367   377930  0.891      Asia
Germany      80.940  3874437   357114  0.916    Europe

In [31]:
df.iloc[1:3, 2]

France     640679
Germany    357114
Name: Surface, dtype: int64

In [32]:
df.iloc[1:3, [1,3]]

             GDP    HDI
France   2833687  0.888
Germany  3874437  0.916

In [33]:
df.iloc[1:3, 1:3]

             GDP  Surface
France   2833687   640679
Germany  3874437   357114

**RECOMMENDED: Always use loc and iloc to reduce ambiguity, specially with DataFrames with numeric indexes.**

<b>Conditional selection (boolean arrays)</b>

In [34]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [35]:
df["Population"] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [36]:
df[df["Population"] > 70]

               Population       GDP  Surface    HDI Continent
Germany            80.940   3874437   357114  0.916    Europe
Japan             127.061   4602367   377930  0.891      Asia
United States     318.523  17348075  9525067  0.915   America

In [37]:
df.loc[df["Population"] > 70, "Population"]

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [38]:
df.loc[df["Population"] > 70, ["Population", "GDP"]]

               Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

### **Dropping stuff**

In [39]:
df.drop("Canada")

                Population       GDP  Surface    HDI Continent
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [40]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [41]:
df.drop(["Canada", "France"])

                Population       GDP  Surface    HDI Continent
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [42]:
df.drop(columns=["Population", "Surface"])

                     GDP    HDI Continent
Canada           1785387  0.913   America
France           2833687  0.888    Europe
Germany          3874437  0.916    Europe
Italy            2167744  0.873    Europe
Japan            4602367  0.891      Asia
United Kingdom   2950039  0.907    Europe
United States   17348075  0.915   America

In [43]:
df.drop(["Canada", "Germany"], axis=0)

                Population       GDP  Surface    HDI Continent
France              63.951   2833687   640679  0.888    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [45]:
df.drop(["Population", "GDP"], axis=1)

                Surface    HDI Continent
Canada          9984670  0.913   America
France           640679  0.888    Europe
Germany          357114  0.916    Europe
Italy            301336  0.873    Europe
Japan            377930  0.891      Asia
United Kingdom   242495  0.907    Europe
United States   9525067  0.915   America

In [46]:
df.drop(["Population", "HDI"], axis="columns")

                     GDP  Surface Continent
Canada           1785387  9984670   America
France           2833687   640679    Europe
Germany          3874437   357114    Europe
Italy            2167744   301336    Europe
Japan            4602367   377930      Asia
United Kingdom   2950039   242495    Europe
United States   17348075  9525067   America

In [48]:
df.drop(["Canada", "Italy"], axis="rows")

                Population       GDP  Surface    HDI Continent
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

## **Operations**

In [49]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [60]:
df[["Population","GDP"]] / 100

                Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

In [61]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [62]:
df[["GDP", "HDI"]]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [63]:
df[["GDP", "HDI"]] + crisis

                       GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

## **Modifying DataFrames**

## <b>Adding a new column

In [70]:
langs = pd.Series(['French', 'German', 'Italian'],
                  index=['France', 'Germany', 'Italy'],
                  name = "language")

In [71]:
langs

France      French
Germany     German
Italy      Italian
Name: language, dtype: object

In [72]:
df["language"] = langs

In [73]:
df

                Population       GDP  Surface    HDI Continent language
Canada              35.467   1785387  9984670  0.913   America      NaN
France              63.951   2833687   640679  0.888    Europe   French
Germany             80.940   3874437   357114  0.916    Europe   German
Italy               60.665   2167744   301336  0.873    Europe  Italian
Japan              127.061   4602367   377930  0.891      Asia      NaN
United Kingdom      64.511   2950039   242495  0.907    Europe      NaN
United States      318.523  17348075  9525067  0.915   America      NaN

In [74]:
#Replace value per columns
df["language"] = "ENGLISH"

In [75]:
df

                Population       GDP  Surface    HDI Continent language
Canada              35.467   1785387  9984670  0.913   America  ENGLISH
France              63.951   2833687   640679  0.888    Europe  ENGLISH
Germany             80.940   3874437   357114  0.916    Europe  ENGLISH
Italy               60.665   2167744   301336  0.873    Europe  ENGLISH
Japan              127.061   4602367   377930  0.891      Asia  ENGLISH
United Kingdom      64.511   2950039   242495  0.907    Europe  ENGLISH
United States      318.523  17348075  9525067  0.915   America  ENGLISH

In [78]:
df.rename(
    columns={
        "GDP" : "Gross Domestic Product",
        "HDI" : "Human Development Index"
    },
    index={
        "United Kingdom" : "UK",
        "United States" : "USA"

    }
    
)

         Population  Gross Domestic Product  ...  Continent  language
Canada       35.467                 1785387  ...    America   ENGLISH
France       63.951                 2833687  ...     Europe   ENGLISH
Germany      80.940                 3874437  ...     Europe   ENGLISH
Italy        60.665                 2167744  ...     Europe   ENGLISH
Japan       127.061                 4602367  ...       Asia   ENGLISH
UK           64.511                 2950039  ...     Europe   ENGLISH
USA         318.523                17348075  ...    America   ENGLISH

[7 rows x 6 columns]

In [79]:
df.rename(index=str.upper)

                Population       GDP  Surface    HDI Continent language
CANADA              35.467   1785387  9984670  0.913   America  ENGLISH
FRANCE              63.951   2833687   640679  0.888    Europe  ENGLISH
GERMANY             80.940   3874437   357114  0.916    Europe  ENGLISH
ITALY               60.665   2167744   301336  0.873    Europe  ENGLISH
JAPAN              127.061   4602367   377930  0.891      Asia  ENGLISH
UNITED KINGDOM      64.511   2950039   242495  0.907    Europe  ENGLISH
UNITED STATES      318.523  17348075  9525067  0.915   America  ENGLISH

In [80]:
df.rename(index=lambda x: x.lower())

                Population       GDP  Surface    HDI Continent language
canada              35.467   1785387  9984670  0.913   America  ENGLISH
france              63.951   2833687   640679  0.888    Europe  ENGLISH
germany             80.940   3874437   357114  0.916    Europe  ENGLISH
italy               60.665   2167744   301336  0.873    Europe  ENGLISH
japan              127.061   4602367   377930  0.891      Asia  ENGLISH
united kingdom      64.511   2950039   242495  0.907    Europe  ENGLISH
united states      318.523  17348075  9525067  0.915   America  ENGLISH

In [81]:
df.rename(index=str.upper)

                Population       GDP  Surface    HDI Continent language
CANADA              35.467   1785387  9984670  0.913   America  ENGLISH
FRANCE              63.951   2833687   640679  0.888    Europe  ENGLISH
GERMANY             80.940   3874437   357114  0.916    Europe  ENGLISH
ITALY               60.665   2167744   301336  0.873    Europe  ENGLISH
JAPAN              127.061   4602367   377930  0.891      Asia  ENGLISH
UNITED KINGDOM      64.511   2950039   242495  0.907    Europe  ENGLISH
UNITED STATES      318.523  17348075  9525067  0.915   America  ENGLISH

In [83]:
#Drop the column
df.drop(columns=["language"], inplace=True)

### **Adding values**

In [84]:
df.append(pd.Series(
    {
        "Population": 3,
      "GDP": 1_000_000
    }, name="China"
))

                Population         GDP    Surface    HDI Continent
Canada              35.467   1785387.0  9984670.0  0.913   America
France              63.951   2833687.0   640679.0  0.888    Europe
Germany             80.940   3874437.0   357114.0  0.916    Europe
Italy               60.665   2167744.0   301336.0  0.873    Europe
Japan              127.061   4602367.0   377930.0  0.891      Asia
United Kingdom      64.511   2950039.0   242495.0  0.907    Europe
United States      318.523  17348075.0  9525067.0  0.915   America
China                3.000   1000000.0        NaN    NaN       NaN

In [86]:
df

                Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [88]:
#You can directly set the new index and values to the DataFrame:
df.loc["China"] = pd.Series(
    {
        "Population": 3,
      "GDP": 1_000_000,
     "Continent":"Asia"
    }
)

In [89]:
df

                Population       GDP    Surface    HDI Continent
Canada              35.467   1785387  9984670.0  0.913   America
France              63.951   2833687   640679.0  0.888    Europe
Germany             80.940   3874437   357114.0  0.916    Europe
Italy               60.665   2167744   301336.0  0.873    Europe
Japan              127.061   4602367   377930.0  0.891      Asia
United Kingdom      64.511   2950039   242495.0  0.907    Europe
United States      318.523  17348075  9525067.0  0.915   America
China                3.000   1000000        NaN    NaN      Asia

In [90]:
df.drop("China", inplace=True)

In [91]:
df

                Population       GDP    Surface    HDI Continent
Canada              35.467   1785387  9984670.0  0.913   America
France              63.951   2833687   640679.0  0.888    Europe
Germany             80.940   3874437   357114.0  0.916    Europe
Italy               60.665   2167744   301336.0  0.873    Europe
Japan              127.061   4602367   377930.0  0.891      Asia
United Kingdom      64.511   2950039   242495.0  0.907    Europe
United States      318.523  17348075  9525067.0  0.915   America

In [92]:
# More radical index changes
df.reset_index()

            index  Population       GDP    Surface    HDI Continent
0          Canada      35.467   1785387  9984670.0  0.913   America
1          France      63.951   2833687   640679.0  0.888    Europe
2         Germany      80.940   3874437   357114.0  0.916    Europe
3           Italy      60.665   2167744   301336.0  0.873    Europe
4           Japan     127.061   4602367   377930.0  0.891      Asia
5  United Kingdom      64.511   2950039   242495.0  0.907    Europe
6   United States     318.523  17348075  9525067.0  0.915   America

In [93]:
df

                Population       GDP    Surface    HDI Continent
Canada              35.467   1785387  9984670.0  0.913   America
France              63.951   2833687   640679.0  0.888    Europe
Germany             80.940   3874437   357114.0  0.916    Europe
Italy               60.665   2167744   301336.0  0.873    Europe
Japan              127.061   4602367   377930.0  0.891      Asia
United Kingdom      64.511   2950039   242495.0  0.907    Europe
United States      318.523  17348075  9525067.0  0.915   America

In [94]:
df.set_index("Population")

                 GDP    Surface    HDI Continent
Population
35.467       1785387  9984670.0  0.913   America
63.951       2833687   640679.0  0.888    Europe
80.940       3874437   357114.0  0.916    Europe
60.665       2167744   301336.0  0.873    Europe
127.061      4602367   377930.0  0.891      Asia
64.511       2950039   242495.0  0.907    Europe
318.523     17348075  9525067.0  0.915   America

In [95]:
df[["Population", "GDP"]]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [96]:
#let's find out gdp per capita and add it to column
df["GDP per Capita"] = df["GDP"] / df["Population"]

In [97]:
df

                Population       GDP  ...  Continent  GDP per Capita
Canada              35.467   1785387  ...    America    50339.385908
France              63.951   2833687  ...     Europe    44310.284437
Germany             80.940   3874437  ...     Europe    47868.013343
Italy               60.665   2167744  ...     Europe    35733.025633
Japan              127.061   4602367  ...       Asia    36221.712406
United Kingdom      64.511   2950039  ...     Europe    45729.239975
United States      318.523  17348075  ...    America    54464.120330

[7 rows x 6 columns]

In [98]:
df.head()

         Population      GDP    Surface    HDI Continent  GDP per Capita
Canada       35.467  1785387  9984670.0  0.913   America    50339.385908
France       63.951  2833687   640679.0  0.888    Europe    44310.284437
Germany      80.940  3874437   357114.0  0.916    Europe    47868.013343
Italy        60.665  2167744   301336.0  0.873    Europe    35733.025633
Japan       127.061  4602367   377930.0  0.891      Asia    36221.712406

In [99]:
df.describe()

       Population           GDP       Surface       HDI  GDP per Capita
count    7.000000  7.000000e+00  7.000000e+00  7.000000        7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429    44952.254576
std     97.249970  5.494020e+06  4.576187e+06  0.016592     6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000    35733.025633
25%     62.308000  2.500716e+06  3.292250e+05  0.889500    40265.998421
50%     64.511000  2.950039e+06  3.779300e+05  0.907000    45729.239975
75%    104.000500  4.238402e+06  5.082873e+06  0.914000    49103.699626
max    318.523000  1.734808e+07  9.984670e+06  0.916000    54464.120330

In [100]:
population = df["Population"]

In [101]:
population.min(), population.max()

(35.467, 318.523)

In [102]:
population.sum()

751.118

In [110]:
population.sum() / len(population)

107.30257142857144

In [103]:
population.mean()

107.30257142857144

In [104]:
population.std()

97.24996987121581

In [105]:
population.var()

9457.556639952383

In [106]:
population.median()

64.511

In [107]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64

In [108]:
population.quantile(.25)

62.308

In [109]:
population.quantile([.2, .4, .6, .8, 1])

0.2     61.3222
0.4     64.1750
0.6     74.3684
0.8    117.8368
1.0    318.5230
Name: Population, dtype: float64